CREATE TABLE user(
	id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	cpf VARCHAR(255) UNIQUE NOT NULL
	password VARCHAR(255) NOT NULL
);

CREATE TABLE card(
	id VARCHAR(255) PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	number varchar(255) NOT NULL,
	date VARCHAR(255) NOT NULL,
	cvv INT NOT NULL,
	user_id VARCHAR(255) NOT NULL,
	FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE payment(
	id VARCHAR(255) PRIMARY KEY,
	amount FLOAT NOT NULL,
	card_number VARCHAR(255) NOT NULL,
	card_id VARCHAR(255) NOT NULL,
	FOREIGN KEY (card_id) REFERENCES card(id)
);