@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiNDEyM2UyLTBkMWEtNGM2Yy05NWU5LWY5YjkzZTVlYTFjOSIsImlhdCI6MTY1ODYxNDU5MCwiZXhwIjoxNjU4NzAwOTkwfQ.wXoTPJXQkqsfUKBJrfr6U1ye4jg5qVk4h8bC5OpM5zQ

###create user

POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "email": "matheus4@gmail.com",
    "password": "123456"
}

###login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "matheus4@gmail.com",
    "password": "123456"
}


###create list
POST http://localhost:3003/list/create/trabalho
Authorization: {{token}}
