@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiNDEyM2UyLTBkMWEtNGM2Yy05NWU5LWY5YjkzZTVlYTFjOSIsImlhdCI6MTY1ODc3NDk3NCwiZXhwIjoxNjU4ODYxMzc0fQ.Nm96jD0WIe80zLHSFYBjPPR-FaZiglDFsVCJ5pLkTs8

###create user

POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "email": "matheus4@gmail.com",
    "password": "123456"
}

###login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "matheus4@gmail.com",
    "password": "123456"
}


###create list
POST http://localhost:3003/list/create/trabalho
Authorization: {{token}}
