###cadastrar competicao
POST https://estantevirtualmatheus.herokuapp.com/competicao/cadastro
Content-Type: application/json

{
   "competicao": "100m rasos",
   "unidade":"s"
}

###pegar todas as competicoes
GET https://estantevirtualmatheus.herokuapp.com/competicao/get

###pegar dados da competicao pelo id
GET https://estantevirtualmatheus.herokuapp.com/competicao/getName
Content-Type: application/json

{
    "id": "5721b389-4e6e-44d1-ab40-ef3f54905dcf"
}

###pegar vencedor
GET https://estantevirtualmatheus.herokuapp.com/competicao/getWinner
Content-Type: application/json

{
    "id": "5721b389-4e6e-44d1-ab40-ef3f54905dcf",
    "definitivo": "FALSE"
}

###cadastrar atleta
POST https://estantevirtualmatheus.herokuapp.com/atleta/cadastro
Content-Type: application/json

{
    "competicaoId": "4a7bc8b7-a674-42c7-8401-70a938d60c67",
    "nome": "joao 10",
    "value1": 12.3,
    "value2": 12.4,
    "value3": 13.1
}

###pegar todos os atletas
GET https://estantevirtualmatheus.herokuapp.com/atleta/getAll

###pegar todos os atletas de uma competicao
GET https://estantevirtualmatheus.herokuapp.com/atleta/getAtletas
Content-Type: application/json

{
    "id": "4a7bc8b7-a674-42"
}